# Generated by Django 3.1.2 on 2020-10-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201011_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
    ]
